// <auto-generated />
namespace BaseEAM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatereci5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatereci5));
        
        string IMigrationMetadata.Id
        {
            get { return "201708270328231_update-reci5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
