// <auto-generated />
namespace BaseEAM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatefilterrek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatefilterrek));
        
        string IMigrationMetadata.Id
        {
            get { return "201707150921328_update-filter-rek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
