// <auto-generated />
namespace BaseEAM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatewot6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatewot6));
        
        string IMigrationMetadata.Id
        {
            get { return "201708230138291_update-wot6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
