//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clickatell.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class StatusSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StatusSettings defaultInstance = ((StatusSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StatusSettings())));
        
        public static StatusSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("001")]
        public string MessageUnknown_Code {
            get {
                return ((string)(this["MessageUnknown_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message unknown")]
        public string MessageUnknown_Description {
            get {
                return ((string)(this["MessageUnknown_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("002")]
        public string MessageQueued_Code {
            get {
                return ((string)(this["MessageQueued_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message queued")]
        public string MessageQueued_Description {
            get {
                return ((string)(this["MessageQueued_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("003")]
        public string DeliveredToGateway_Code {
            get {
                return ((string)(this["DeliveredToGateway_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delivered to gateway")]
        public string DeliveredToGateway_Description {
            get {
                return ((string)(this["DeliveredToGateway_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("004")]
        public string ReceivedByRecipient_Code {
            get {
                return ((string)(this["ReceivedByRecipient_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Received by recipient")]
        public string ReceivedByRecipient_Description {
            get {
                return ((string)(this["ReceivedByRecipient_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("005")]
        public string ErrorWithMessage_Code {
            get {
                return ((string)(this["ErrorWithMessage_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error with message")]
        public string ErrorWithMessage_Description {
            get {
                return ((string)(this["ErrorWithMessage_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("006")]
        public string MessageCancelled_Code {
            get {
                return ((string)(this["MessageCancelled_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User cancelled message delivery")]
        public string MessageCancelled_Description {
            get {
                return ((string)(this["MessageCancelled_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("007")]
        public string ErrorDeliveringMessage_Code {
            get {
                return ((string)(this["ErrorDeliveringMessage_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error delivering message")]
        public string ErrorDeliveringMessage_Description {
            get {
                return ((string)(this["ErrorDeliveringMessage_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("008")]
        public string MessageReceivedByGateway_Code {
            get {
                return ((string)(this["MessageReceivedByGateway_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OK")]
        public string MessageReceivedByGateway_Description {
            get {
                return ((string)(this["MessageReceivedByGateway_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("009")]
        public string RoutingError_Code {
            get {
                return ((string)(this["RoutingError_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Routing error")]
        public string RoutingError_Description {
            get {
                return ((string)(this["RoutingError_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("010")]
        public string MessageExpired_Code {
            get {
                return ((string)(this["MessageExpired_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message expired")]
        public string MessageExpired_Description {
            get {
                return ((string)(this["MessageExpired_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("011")]
        public string MessageQueuedForLaterDelivery_Code {
            get {
                return ((string)(this["MessageQueuedForLaterDelivery_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message queued for later delivery")]
        public string MessageQueuedForLaterDelivery_Description {
            get {
                return ((string)(this["MessageQueuedForLaterDelivery_Description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("012")]
        public string OutOfCredit_Code {
            get {
                return ((string)(this["OutOfCredit_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Out of credit")]
        public string OutOfCredit_Desciption {
            get {
                return ((string)(this["OutOfCredit_Desciption"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("014")]
        public string MaximumMTLimit_Code {
            get {
                return ((string)(this["MaximumMTLimit_Code"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximum MT limit exceeded")]
        public string MaximumMTLimit_Desciption {
            get {
                return ((string)(this["MaximumMTLimit_Desciption"]));
            }
        }
    }
}
