/*******************************************************
 * Copyright 2016 (C) BaseEAM Systems, Inc
 * All Rights Reserved
*******************************************************/
using System;
using System.Collections.Generic;

namespace BaseEAM.Core.Domain
{
    public class Assignment : BaseEntity
    {
        /// <summary>
        /// The entity that this assignment attached to
        /// </summary>
        public long? EntityId { get; set; }
        public string EntityType { get; set; }

        public string Number { get; set; }
        public string Description { get; set; }
        public int? Priority { get; set; }
        public string AssignmentType { get; set; }
        public decimal? AssignmentAmount { get; set; }
        public string Comment { get; set; }
        public string AvailableActions { get; set; }
        public string TriggeredAction { get; set; }

        /// <summary>
        /// The datetime that this assignment is expected to start
        /// </summary>
        public DateTime? ExpectedStartDateTime { get; set; }

        /// <summary>
        /// The datetime that this assignment is overdue
        /// </summary>
        public DateTime? DueDateTime { get; set; }

        /// <summary>
        /// The WorkflowInstanceId as generated by WF
        /// </summary>
        public string WorkflowInstanceId { get; set; }

        public long WorkflowDefinitionId { get; set; }

        /// <summary>
        /// The version of Workflow Definition
        /// </summary>
        public int? WorkflowVersion { get; set; }

        /// <summary>
        /// The list of users this assignment assigned to
        /// </summary>
        private ICollection<User> _users;
        public virtual ICollection<User> Users
        {
            get { return _users ?? (_users = new List<User>()); }
            protected set { _users = value; }
        }
    }
}
